version: 2.1

orbs:
  ci: kydeps/ci@dev:alpha

jobs:
  say-hello:
    executor: ci/kydeps
    steps:
      - checkout
      - run:
          name: "Say hello to CMake"
          command: "cmake --version"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
