version: 2.1

orbs:
  ci: kydeps/ci@dev:alpha

jobs:
  say-hello:
    executor: ci/kydeps
    steps:
      - checkout
      - run:
          name: "Say hello to CMake"
          command: "cmake --version"

  build:
    executor: ci/kydeps
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: mkdir build
      - run: cmake -S . -B build
      - run: cmake --build build
      - run: build/tests

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - build
